version: '3.2'
services:
  web:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - "5001:5001"
  test:
    image: webapp-flask-test
    build:
      context: .
      dockerfile: Dockerfile-tests
